os: Visual Studio 2019

branches:
  only:
    - master

install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe

skip_commits:
  files:
    - .gitattributes
    - .gitignore
    - LICENSE
    - README.md

only_commits:
  files:
    - src/
    - test/

before_build:
  - dotnet --version
  - dotnet restore ./src/Bit.Logger
  - dotnet restore ./test/Bit.Logger.Tests

build_script:
  # Build and pack project 
  - dotnet build ./src/Bit.Logger -c Release -o ./artifacts/build
  - dotnet pack ./src/Bit.Logger -c Release -o ./artifacts/nupkg

test_script:
  # Build and run tests project
  - dotnet build ./test/Bit.Logger.Tests -c Release
  - dotnet test ./test/Bit.Logger.Tests -c Release --no-build 

artifacts:
  - path: ./artifacts/nupkg/*.nupkg
  - path: ./artifacts/build/*.dll

deploy:
  provider: NuGet
  api_key:
    secure: jIDNhfirXrO0F6SxjDo5Bz8R2KjexjgtXb7GBI7Sch+fWVW25chDavaarkHk1hdw
  skip_symbols: true
  artifact: /.*\.nupkg/
