os: Visual Studio 2019

branches:
  only:
    - master

install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe

skip_commits:
  files:
    - .gitattributes
    - .gitignore
    - LICENSE
    - README.md

only_commits:
  files:
    - src/
    - test/

environment:
  COVERALLS_REPO_TOKEN:
    secure: 0n47+7c3YiptuHdHw7IBRhdFghphRyIbAQ2u0HiUV8D8mE2AqBK17naDGOuvM1/q

before_build:
  - dotnet --version
  - dotnet restore ./src/Bit.Logger
  - dotnet restore ./test/Bit.Logger.Tests

build_script:
  # Build and pack project 
  - dotnet build ./src/Bit.Logger -c Release -o ./artifacts/build
  - dotnet pack ./src/Bit.Logger -c Release -o ./artifacts/nupkg

test_script:
  # Build tests project
  - dotnet build ./test/Bit.Logger.Tests -c Release

after_test:
  # Run tests and create coverage file to send to coveralls.io
  - dotnet test ./test/Bit.Logger.Tests -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="../coverage.xml" /p:Include=\"[Bit.Logger]\" /p:Exclude=\"[Bit.Logger]Bit.Logger.Migrations.*\"
  - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\coveralls.io'))[0].FullName + '\tools\coveralls.net.exe' + ' --opencover ./test/coverage.xml --full-sources false')

artifacts:
  - path: ./artifacts/nupkg/*.nupkg
  - path: ./artifacts/build/*.dll

deploy:
  provider: NuGet
  api_key:
    secure: wc3eN7SnqhLFIe8Ipvg3/YGb8uEiSJO8j/JjSicR2UzoaVdRSEaDf84NnF9Xp86Q
  skip_symbols: true
  artifact: /.*\.nupkg/
  
