language: csharp
dist: trusty
mono: none
dotnet: 2.1.300

install:
- dotnet restore

script:
- dotnet build Bit.Logger -c Release
- dotnet test Bit.Logger.Tests -c Release
- dotnet publish Bit.Logger -f netcoreapp2.1 -c Release