language: csharp
dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required
mono: none

script:
- sudo snap alias dotnet-sdk.dotnet dotnet

install:	
- dotnet --version
- dotnet restore ./src/Bit.Logger
- dotnet restore ./test/Bit.Logger.Tests

script:	
- dotnet build ./src/Bit.Logger -c Release
- dotnet test ./test/Bit.Logger.Tests -c Release
