language: csharp
dist: trusty
mono: none
dotnet: 2.2 # SDK Version

install:
- dotnet --version
- dotnet restore ./src/Bit.Logger
- dotnet restore ./tests/Bit.Logger.Tests

script:
- dotnet build ./src/Bit.Logger -c Release
- dotnet test ./tests/Bit.Logger.Tests -c Release
- dotnet pack ./src/Bit.Logger -c Release -o ../../artifacts/nupkg /p:PackageVersion=1.0.6
- dotnet publish ./src/Bit.Logger -c Release -o ../../artifacts/build/1.0.6