language: csharp
dist: bionic
sudo: required
mono: none
dotnet: 3.1 # SDK Version

install:	
- dotnet --version
- dotnet restore ./src/Bit.Logger
- dotnet restore ./test/Bit.Logger.Tests

script:	
- dotnet build ./src/Bit.Logger -c Release
- dotnet test ./test/Bit.Logger.Tests -c Release
