language: csharp
dist: trusty
mono: none
dotnet: 2.1.300 # SDK Version

install:
- dotnet --version
- dotnet restore ./src/Bit.Logger -r netcoreapp2.1
- dotnet restore ./tests/Bit.Logger.Tests -r netcoreapp2.1

script:
- dotnet build ./src/Bit.Logger -c Release -f netcoreapp2.1
- dotnet test ./tests/Bit.Logger.Tests -c Release -f netcoreapp2.1
- dotnet pack ./src/Bit.Logger -c Release --runtime netcoreapp2.1 -o ../../artifacts/nupkg /p:PackageVersion=1.0.6
- dotnet publish ./src/Bit.Logger -c Release -f netcoreapp2.1 -o ../../artifacts/build/1.0.6