os: Visual Studio 2017
build: off

skip_commits:
  files:
    - .gitattributes
    - .gitignore
    - LICENSE
    - README.md

environment:
  COVERALLS_REPO_TOKEN:
    secure: 0n47+7c3YiptuHdHw7IBRhdFghphRyIbAQ2u0HiUV8D8mE2AqBK17naDGOuvM1/q

before_test:
  - dotnet --info
  - dotnet restore

test_script:
  # Build sample
  - dotnet build Bit.Logger -c Release
  - dotnet test Bit.Logger.Tests -c Release

after_test:
  # Build and pack source
  - dotnet test Bit.Logger.Tests -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="../coverage.xml" /p:Exclude=\"[xunit.*]*,[Bit.Logger]Bit.Logger.Migrations.*\"
  - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\coveralls.io'))[0].FullName + '\tools\coveralls.net.exe' + ' --opencover coverage.xml --full-sources false')
  - dotnet publish Bit.Logger -f netcoreapp2.1 -c Release