os: Visual Studio 2017
build: off

environment:
  COVERALLS_REPO_TOKEN:
    secure: 0n47+7c3YiptuHdHw7IBRhdFghphRyIbAQ2u0HiUV8D8mE2AqBK17naDGOuvM1/q

before_test:
  - dotnet --info
  - dotnet restore

test_script:
  # Build sample
  - dotnet test Bit.Logger.Tests

after_test:
  # Build and pack source
  - dotnet test Bit.Logger.Tests -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='../cover.xml'
  - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\coveralls.io'))[0].FullName + '\tools\coveralls.net.exe' + ' --opencover coverage.xml')
  - dotnet publish Bit.Logger -f netcoreapp2.1 -c Release