os: Visual Studio 2017

branches:
  only:
    - master

install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe

skip_commits:
  files:
    - .gitattributes
    - .gitignore
    - LICENSE
    - README.md

environment:
  COVERALLS_REPO_TOKEN:
    secure: 0n47+7c3YiptuHdHw7IBRhdFghphRyIbAQ2u0HiUV8D8mE2AqBK17naDGOuvM1/q

before_build:
  - dotnet --version
  - dotnet restore ./src/Bit.Logger
  - dotnet restore ./tests/Bit.Logger.Tests

build_script:
  # Build, pack and publish project 
  - dotnet build ./src/Bit.Logger -c Release
  - dotnet pack ./src/Bit.Logger -c Release -o ../../artifacts/nupkg /p:PackageVersion=1.0.6
  - dotnet publish ./src/Bit.Logger -c Release -o ../../artifacts/build/1.0.6

test_script:
  # Build tests project
  - dotnet build ./tests/Bit.Logger.Tests -c Release

after_test:
  # Run tests and create coverage file to send to coveralls.io
  - dotnet test ./tests/Bit.Logger.Tests -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="../coverage.xml" /p:Exclude=\"[xunit.*]*,[Bit.Logger]Bit.Logger.Migrations.*\"
  - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\coveralls.io'))[0].FullName + '\tools\coveralls.net.exe' + ' --opencover ./tests/coverage.xml --full-sources false')

artifacts:
  - path: ./artifacts/nupkg/*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: +2AaGHKoOIWmNfKFxki/UbdUAek+BS82xkNBx31eB4YM3mdN/a5mCX3eamZIwqsm
  skip_symbols: true
  artifact: /.*\.nupkg/
